{
  "formatVersion": "1.1",
  "component": {
    "group": "sample.recyclerview",
    "module": "recyclerview",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "sample.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.3.1.aar",
          "url": "recyclerview-1.3.1.aar",
          "size": 408889,
          "sha512": "28cd0b35e663ecee6d766ed98bb9e6e2de0fd19df02739dde460ad2568c21f4363f55d5046ae4887f0555ea8b82bfc61075e70906fb1c1cb105c5d77d3d6dc6f",
          "sha256": "4cfed42bdcc196d11e9b10da68c1f96cd4bda4cd8521e7285f62442c0c11de08",
          "sha1": "3cb90a3c17fbb25e196f069101d99cd2f024d974",
          "md5": "f43347ae617e4c4f4445bcf68248a49d"
        }
      ]
    }
  ]
}
